#!/usr/bin/env python3
"""claude-context-meter — registers the status line and the hooks in settings.json.

Usage:  python3 src/install_settings.py <install_dir> [--uninstall] [--dry-run]

Idempotent and additive. The installer only touches what it owns:

  * `statusLine` — the sensor. REQUIRED, not optional: without it the window
    size cannot be measured and the meter falls back to the honest but sparse
    unknown display. If a foreign status line is already registered it is NOT
    overwritten but wrapped in a script that calls it and passes its output
    through.
  * `hooks.Stop` — the dashboard. An entry from a predecessor (context-meter,
    session-context-alarm) is replaced so two dashboards cannot fire at once.
    Unrelated Stop hooks are left alone.
  * `hooks.SessionStart` — the model line. Added; unrelated SessionStart hooks
    (a vault loader, say) are preserved.

A timestamped backup is written before every change.
"""
import sys, os, json, shutil, time

HOME = os.path.expanduser("~")
SETTINGS = os.path.join(HOME, ".claude", "settings.json")

# How the installer recognises its own entries and superseded ones.
OWNED_MARKERS = ("context-meter", "context_meter", "session-context-alarm",
                 "session_start.py", "sensor.py")


def load(path):
    try:
        with open(path) as f:
            return json.load(f)
    except FileNotFoundError:
        return {}
    except Exception as e:
        sys.exit("settings.json is not readable (%s) — aborting, nothing changed." % e)


def backup(path):
    if not os.path.exists(path):
        return None
    dst = "%s.bak-%s" % (path, time.strftime("%Y%m%d-%H%M%S"))
    shutil.copy2(path, dst)
    return dst


def is_ours(cmd):
    return any(m in (cmd or "") for m in OWNED_MARKERS)


def strip_ours(settings, event):
    """Remove our own/superseded entries from a hook event, keep foreign ones."""
    groups = settings.get("hooks", {}).get(event) or []
    kept, removed = [], []
    for g in groups:
        hooks = [h for h in (g.get("hooks") or []) if not is_ours(h.get("command"))]
        removed += [h["command"] for h in (g.get("hooks") or []) if is_ours(h.get("command"))]
        if hooks:
            g = dict(g, hooks=hooks)
            kept.append(g)
        elif not g.get("hooks"):
            kept.append(g)
    if kept:
        settings.setdefault("hooks", {})[event] = kept
    else:
        settings.get("hooks", {}).pop(event, None)
    return removed


def add_hook(settings, event, command, timeout=None):
    entry = {"type": "command", "command": command}
    if timeout:
        entry["timeout"] = timeout
    groups = settings.setdefault("hooks", {}).setdefault(event, [])
    for g in groups:
        if g.get("matcher", "") == "":
            g.setdefault("hooks", []).append(entry)
            return
    groups.append({"matcher": "", "hooks": [entry]})


def install(install_dir, dry_run=False):
    src = os.path.join(install_dir, "src")
    sensor = os.path.join(src, "sensor.py")
    meter = os.path.join(src, "context_meter.py")
    start = os.path.join(src, "session_start.py")
    for p in (sensor, meter, start):
        if not os.path.exists(p):
            sys.exit("Missing: %s — run install.sh first." % p)

    settings = load(SETTINGS)
    log = []

    # --- status line (sensor) ----------------------------------------------
    sl = settings.get("statusLine")
    cmd = 'python3 "%s"' % sensor
    if isinstance(sl, dict) and sl.get("command") and not is_ours(sl["command"]):
        wrapper = os.path.join(install_dir, "statusline", "wrapper.sh")
        if not dry_run:
            os.makedirs(os.path.dirname(wrapper), exist_ok=True)
            with open(wrapper, "w") as f:
                f.write(
                    "#!/bin/sh\n"
                    "# Generated by claude-context-meter. Runs the sensor AND the\n"
                    "# previously registered status line, and prints its output.\n"
                    "input=$(cat)\n"
                    'printf "%%s" "$input" | python3 "%s" >/dev/null 2>&1\n'
                    'printf "%%s" "$input" | %s\n' % (sensor, sl["command"])
                )
            os.chmod(wrapper, 0o755)
        settings["statusLine"] = {"type": "command", "command": wrapper}
        log.append("Status line: existing line wrapped → %s" % wrapper)
    else:
        settings["statusLine"] = {"type": "command", "command": cmd, "padding": 0}
        log.append("Status line: sensor registered (%s)" % ("new" if not sl else "updated"))

    # --- Stop hook (dashboard) ----------------------------------------------
    for old in strip_ours(settings, "Stop"):
        log.append("Stop: removed superseded entry → %s" % old)
    add_hook(settings, "Stop", 'python3 "%s"' % meter, timeout=10)
    log.append("Stop: dashboard registered")

    # --- SessionStart (model line) ------------------------------------------
    for old in strip_ours(settings, "SessionStart"):
        log.append("SessionStart: removed superseded entry → %s" % old)
    add_hook(settings, "SessionStart", 'python3 "%s"' % start, timeout=5)
    log.append("SessionStart: model line registered (foreign hooks kept)")

    return settings, log


def uninstall():
    settings = load(SETTINGS)
    log = []
    sl = settings.get("statusLine")
    if isinstance(sl, dict) and is_ours(sl.get("command")):
        settings.pop("statusLine", None)
        log.append("Status line removed")
    for event in ("Stop", "SessionStart"):
        for old in strip_ours(settings, event):
            log.append("%s removed → %s" % (event, old))
    if not log:
        log.append("Nothing to remove — no context-meter entries in settings.json")
    return settings, log


def main():
    args = sys.argv[1:]
    dry = "--dry-run" in args
    args = [a for a in args if not a.startswith("--")]
    if "--uninstall" in sys.argv:
        settings, log = uninstall()
    else:
        if not args:
            sys.exit("Usage: install_settings.py <install_dir> [--uninstall] [--dry-run]")
        settings, log = install(os.path.abspath(args[0]), dry_run=dry)

    if dry:
        print("--- dry run, nothing written ---")
        for line in log:
            print("  " + line)
        print(json.dumps({k: settings.get(k) for k in ("statusLine", "hooks")},
                         indent=2, ensure_ascii=False))
        return

    b = backup(SETTINGS)
    os.makedirs(os.path.dirname(SETTINGS), exist_ok=True)
    tmp = SETTINGS + ".tmp"
    with open(tmp, "w") as f:
        json.dump(settings, f, indent=2, ensure_ascii=False)
        f.write("\n")
    os.replace(tmp, SETTINGS)

    for line in log:
        print("  " + line)
    if b:
        print("  Backup: %s" % b)


if __name__ == "__main__":
    main()
